module Hork.Header where

import Hork.Mem

-- Constants for the locations of things in the header.

hdrVERSION, hdrFLAGS1, hdrHIMEM, hdrPC0, hdrDICTIONARY, hdrOBJTABLE, hdrGLOBALS, hdrSTATIC, hdrFLAGS2, hdrABBREVIATIONS, hdrFILESIZE, hdrCHECKSUM, hdrINTNUMBER, hdrINTVERSION, hdrSTANDARD :: RA
hdrVERSION = 0
hdrFLAGS1 = 1
hdrHIMEM = 4
hdrPC0 = 6
hdrDICTIONARY = 8
hdrOBJTABLE = 0xA
hdrGLOBALS = 0xC
hdrSTATIC = 0xE
hdrFLAGS2 = 0x10
hdrABBREVIATIONS = 0x18
hdrFILESIZE = 0x1A
hdrCHECKSUM = 0x1C
hdrINTNUMBER = 0x1E
hdrINTVERSION = 0x1F
hdrSTANDARD = 0x32

hdrSCREEN_HEIGHT_CHARS, hdrSCREEN_WIDTH_CHARS, hdrSCREEN_HEIGHT_UNITS, hdrSCREEN_WIDTH_UNITS, hdrFONT_WIDTH_UNITS, hdrFONT_HEIGHT_UNITS :: RA
hdrSCREEN_HEIGHT_CHARS = 0x20
hdrSCREEN_WIDTH_CHARS  = 0x21
hdrSCREEN_HEIGHT_UNITS = 0x22
hdrSCREEN_WIDTH_UNITS  = 0x24
hdrFONT_WIDTH_UNITS    = 0x26
hdrFONT_HEIGHT_UNITS   = 0x27

